#!/bin/sh
#
# A little trick to shut down mdnsd when a port is closed.
#

set -o monitor

# We can pass in another process as argument, for testing
MDNSD="${1:-sbin/mdnsd}"

cleanup () {
  echo "Killing process $MDNSD (pid $MDNSD_PID)"
  kill -15 "$MDNSD_PID"
}

trap cleanup EXIT
trap "echo Received SIGINT; exit" INT
trap "echo Received SIGTERM; exit" TERM
trap "echo Child process died; exit" CHLD

$MDNSD -debug &
MDNSD_PID=$!

echo "Started $MDNSD with PID $MDNSD_PID"

# Read line from this process. If we terminate, we will shut down
# our child process with a little force.
read LINE
